namespace PessoasApi.Application.People.Queries;

public static class MedievalNamesCatalog
{
    public static readonly IReadOnlyList<string> MaleNames = ParseNames(
        """
        Herbert
        Hubert
        Humberto
        Ivamberto
        João
        Julian
        Julião
        José
        Donaldo
        Silva
        Eugênio
        Martin
        Leandro
        Leonardo
        Riobaldo
        Pícaro
        Daniel
        Victor
        Ramiro
        Manfredo
        Porcão
        Elias
        Jairo
        Manuel
        Palácius
        Carlos
        Euzébio
        Irineu
        Lívius
        Máximus
        Pilatos
        Spilman
        Cristian
        Carlitos
        Alceu
        Polinésio
        Gordon
        Sísifo
        Ícaro
        Igor
        Gordo
        Matador
        Samuel
        Jamiel
        Eurico
        Letício
        Heleno
        Denis
        Menelau
        Sócrates
        Epicuro
        Eratóstenes
        Heráclito
        Satanaz
        Demócrito
        Skylab
        Locke
        Louco
        Índio
        Tobias
        John
        Paul
        Maligno
        Benigno
        Alberto
        Justino
        Francisco
        Laerte
        Isaque
        Apu
        Moe
        Mickey
        Isaías
        Chorão
        Henrique
        Louis
        Casimiro
        Orlando
        Sebastião
        Sebastian
        Javé
        Zidane
        Milton
        Elton
        Selton
        Newton
        Amaranto
        Amarante
        Neófito
        Filisteu
        Doente
        Tibúrcio
        Hércules
        Perseu
        Teseu
        Espanhol
        Chinês
        Hector
        Marcolino
        Francolino
        Tristão
        César
        Júlio
        Cômodo
        Joaquim
        Fênix
        Bruce
        Nicolas
        Hermeto
        Ernesto
        Anfitrião
        Moisés
        Erik
        Érico
        Jaques
        Pierre
        Patrício
        Patrick
        Normando
        Normam
        Adam
        Adão
        Leitão
        Leão
        Cavalo
        Inácio
        Frido
        Fredo
        Alfredo
        Godofredo
        Figueiredo
        Horácio
        Átila
        Hermes
        Ulisses
        Alexandre
        Agamenon
        Aquiles
        Odisseu
        Coríntios
        Morfeu
        Orfeu
        Brancaleone
        Napoleão
        Adolfo
        Antônio
        Moacir
        Euzébio
        Cristóvão
        Mephisto
        Baltazar
        Belchior
        Burgos
        Ubirajara
        Ptolomeu
        Próximo
        Asterix
        Obelix
        Willian
        Guilherme
        Lúcio
        Raul
        Demétrios
        Lester
        Chester
        Walter
        Wagner
        Valdir
        Pedro
        Pedroso
        Pedreiro
        Alberto
        Roberto
        Oscar
        Osmar
        Javier
        Buzuzima
        Bráulio
        Plínio
        Miro
        Quaderna
        Torquemada
        Ademar
        Mudinho
        Capeta
        Odorico
        Odoacro
        Teodorico
        Cassandro
        Olavo
        Mariano
        Justo
        Roderigo
        Juarez
        Antônio
        Adair
        Damaceno
        Valdemar
        Jair
        Cecílio
        Simon
        Lázaro
        Ari
        Frederico
        Derico
        Quasímodo
        Falabela
        Binho
        Cândido
        Graciano
        Hugo
        Afredo
        Dario
        Luís
        Garibaldi
        Dagoberto
        Guilherme
        Bismark
        Trotski
        Stalin
        Lenin
        Maneta
        Caolho
        Zureta
        Ziraldo
        Zurita
        Nelson
        Otto
        Lobisomen
        Bucéfalo
        Madruga
        Filipesco
        Clóvis
        Orelhudo
        Maricas
        Olegário
        Sigfrido
        Sigismundo
        Gado
        Aranha
        Ronaldo
        Bill
        Faber
        Wagner
        Fedorento
        Camilo
        Tonho
        Flamingo
        Lucius
        Simonal
        Vanderlei
        Galvão
        Camendongo
        Ifrit
        Rudinei
        Bolívar
        Bondoso
        Pepino
        Gaguinho
        Ocelot
        Anatole
        Hipólito
        Percival
        Rubinho
        Peralta
        Aquilante
        Zampàno
        Saibara
        Peregrino
        Oráculo
        Vespúcio
        Tirolês
        Glauco
        Vilson
        Lingüiça
        Augusto
        Ariosvaldo
        Virgílio
        Quincas
        Lázaro
        Minuano
        Valentin
        Ingmar
        Carniceiro
        Adenauer
        Godard
        Raimundo
        Píramo
        Nicolau
        George
        Bruce
        Vinícius
        Lucrécio
        Abelardo
        Dario
        Benjamim
        Teodorico
        Emilio
        Basílio
        Caolho
        Henrique
        Persivaldo
        Casimiro
        Aramis
        Armand
        Rui
        Amarante
        Blanca
        Miro
        Aragão
        Vilson
        Gafgarião
        Garvas
        Otávio
        Valentino
        Tolentino
        Graciano
        Bryan
        Rômulo
        Armando
        Ezequiel
        Natan
        Édipo
        Silvio
        Simon
        Simão
        Bartolomeu
        Baltazar
        Juan
        Bernardo
        Eduardo
        Homero
        Evandro
        Guilherme
        Antônio
        Cícero
        Silas
        Tadeu
        Judas
        Julião
        Julian
        Júlio
        Osmar
        Marcos
        Milton
        Radamés
        Mauro
        Bagoas
        Isidoro
        Izaías
        Vinícius
        Enéas
        Benjamim
        Morfeu
        Orfeu
        Saulo
        Saul
        Dionísio
        Baco
        Horácio
        Rafael
        Amarante
        Cássio
        Éverton
        Inácio
        João
        Lucas
        Cândido
        Samuel
        Paulo
        Vitor
        Elgar
        Cervantes
        André
        Adan
        Parmênion
        Olímpio
        Miro
        Malaquias
        Fernando
        Alceu
        Tristão
        Cronos
        Jonas
        Édipo
        Silvio
        Zacarias
        Pablo
        Telêmaco
        Quênia
        Gúliver
        Homer
        Miguel
        Ronaldo
        Fujin
        Waldir
        Gregório
        Ferdinando
        Ivan
        Dalton
        Lauro
        Bóris
        Cleiton
        Marcos
        Ramiro
        Marlon
        Damião
        Raul
        Apolo
        Joel
        Grendel
        Camus
        Alberto
        Salmôneos
        Filipesco
        Juanito
        Plínio
        Denilson
        Adilson
        Garvas
        Pompeu
        Aladar
        Bóris
        Daniel
        Leonel
        Siegfried
        Martin
        Martinho
        Jonatan
        Natanael
        Eurico
        Cecílio
        Tiago
        Canon
        Oscar
        Olaf
        Ajax
        Frido
        Cristian
        Blanca
        Adolfo
        Leandro
        Ângelo
        Golias
        Cleber
        Argos
        Hermínio
        Herman
        Normando
        Goro
        Chiburgo
        Petrúquio
        Celso
        Juremir
        Barcelos
        Tirolês
        Batistuta
        Sancho
        Alonso
        Afonso
        Firitóbulo
        Lancelot
        Arthur
        Espiridião
        Jacinto
        Magnus
        Magno
        Galileu
        Olívio
        Oliver
        Heféstio
        Marisqueiro
        Douglas
        Osvaldo
        Febrônio
        Pícaro
        Funâmbulo
        Visigodo
        Michelângelo
        Salazar
        Caliban
        Patolino
        Timão
        Timóteo
        Eriberto
        Egberto
        Gomez
        Brutus
        Fausto
        Faustino
        Judas
        Sukamon
        Neimateuminto
        Hugo
        Beti
        Redmond
        Barry
        Barnabé
        Miconga
        Rolando
        Roland
        Filadelfo
        Elfgar
        Leofrigo
        Samir
        Ibraim
        Ali
        Etevaldo
        Marcel
        Tango
        Anatole
        Zidane
        Calhorda
        Rubião
        Geremias
        Donatelo
        """);

    public static readonly IReadOnlyList<string> FemaleNames = ParseNames(
        """
        Lia
        Laia
        Lena
        Ana
        Maria
        Joana
        Madalena
        Lilith
        Eva
        Calipso
        Ágata
        Pandora
        Monalisa
        Marisa
        Rosa
        Iracema
        Juliana
        Nastácia
        Odara
        Camila
        Diana
        Rosalinda
        Daiana
        Mariana
        Letícia
        Eleonor
        Isolda
        Isadora
        Celeste
        Brigite
        Greta
        Helga
        Fernanda
        Amanda
        Lisandra
        Elisa
        Elizete
        Elisandra
        Uriko
        Fox
        Penélope
        Xena
        Sheeva
        Helena
        Malena
        Isabel
        Isabela
        Laura
        Lara
        Mikado
        Miluda
        Mia
        Renata
        Leona
        Clara
        Joaquina
        Filomena
        Carina
        Patrícia
        Tisbe
        Lilica
        Oksana
        Vera
        Euvira
        Marta
        Mariana
        Juliana
        Júlia
        Agnes
        Chica
        Gabriela
        Rosana
        Letícia
        Dalila
        Priscila
        Vanessa
        Frida
        Freya
        Abgail
        Cacilda
        Cássia
        Carol
        Carolina
        Cassandra
        Matilde
        Matilda
        Messalina
        Lucrécia
        Diana
        Artemis
        Beatrix
        Verônica
        Daniela
        Ursula
        Rebeca
        Ovelia
        Lolita
        Lola
        Dolores
        Isolda
        Cloroquina
        Roxana
        Minerva
        Inês
        Guíniver
        Lurdes
        Filipesca
        Catarina
        Teresa
        Brigite
        Atena
        Marin
        Sheena
        Sheeva
        Sora
        Mimi
        Cari
        Elza
        Nara
        Rosalinda
        Olívia
        Paquette
        Cunegunda
        Abigail
        Rebeca
        Titânia
        Ana
        Roberta
        Laura
        Joana
        Cornélia
        Ofélia
        Atena
        Rosa
        Agnes
        Vanda
        Mariana
        Alana
        Samanta
        Elisa
        Pandora
        Aline
        Aurora
        Mia
        Freya
        Jô
        Bruna
        Vivi
        Anastássia
        Joaquina
        Sophia
        Sophitia
        Agrias
        Valéria
        Morgana
        Taís
        Josefina
        Lívia
        Lucila
        Perséfone
        Griselda
        Jurema
        Natália
        Periquita
        Cassandra
        Desdêmona
        Rita
        Chimene
        Jocasta
        Alexandra
        Chiquinha
        Cleópatra
        Cornélia
        Calpúrnia
        Madalena
        Bolena
        Emília
        Sônia
        Hebe
        Genebra
        Guinever
        Margarina
        Poliana
        Mina
        Galega
        Clarice
        Clarissa
        Efigênia
        Eugênia
        Greta
        Clementina
        Dulcinéia
        Esther
        Eva
        Griselda
        Zelda
        Raquel
        Florentina
        Secretária
        Catita
        Paloma
        Adúltera
        Dançarina
        Luna
        Karen
        Pópori
        Ann
        Eulália
        Celeste
        Tanajura
        Shiva
        Godiva
        Saga
        Desempregada
        Estela
        Doroteia
        """);

    private static IReadOnlyList<string> ParseNames(string block) =>
        block
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
}
